### ISSUE TITLE
Suggested change of UI workflow

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#100]
After living with the new project structure from #61 for a while, one thing stands out to me as more problematic than intended: Customising the HUD, including verb/action menu, inventory and dialogue. One of the goals was to make it easier to know which scenes to customise by moving the child scenes of hud into a separate directory for game specific files, and later project settings for action menu and inventory was added to avoid having to alter `ui/hud.tscn`.

In hindsight, I don't think these changes made anything easier, since you still can't configure everything in one place, and using project settings to configure the hud means you can only have a single hud in any game, making it impossible (or at least very difficult) to implement minigame scenes as discussed in #84. It also forced the need for workarounds like #80.

The way things were organized before, this would have been easier, and I think the main problem was lack of example implementation and documentation. My suggestion is that we provide a set of template hud scenes, inventories and verb/action menus, to make it easier to customise. To use different implementations in a game, a developer would then only need to configure multiple `game.tscn` scenes with different hud elements that they include in the different rooms as needed, which in my opinion will be more intuitive to a developer and it would also require less code for us to support.

**Comment by mjtorn** [comment]
I think this is a good idea. The essential part of #80 - to me - is `game_am.tscn` which pretty much is all about configuring your game scene. There shouldn't be a practical reason not to provide more examples for the developer to choose from.

Back in the Unity asset world, it wouldn't be uncommon to have a wizard (not the kind with a pointy hat) do the initial setup, and I always envisioned that if Escoria becomes an asset, it would have to have a similar feature.

I fear that there may be dragons where the HUDs need to implement some common API. There are already some if/else clauses, which feel like there should be a better way, but they have the virtue of working and not being too messy. With a huge amount of very different HUDs in different game scenes, and documentation on how to DIY, the design questions may come up. Should that be deferred until later, so that the current ones are simply made into examples and the documentation updated accordingly?

Do you have a directory structure in mind for this?

**Comment by fleskesvor** [comment]
Yes, the "workarounds" in #80, `game_am.tscn` and `hud_minimal.tscn`, are essentially how this can be achieved with a more building blocks like approach, like how you design a room, and less configuration and code. #80 also included a good set of instructions that we can build upon.

I haven't figured out a good directory structure for this yet, but I'm open for ideas. I figure the scenes should perhaps be under `templates/ui/`, but then they won't work without being copied into `game/ui`, because it's not under the resource path, which may be a good thing, because then you're forced to sort out the dependencies initially and your files won't suddenly change when you pull updates from upstream. And do we want to teach developers that `game.tscn` is also a part of the UI by putting it there? It kind of is, so I suppose it makes sense.

While developing the templates, they could live in `demo/ui`, and have resource paths pointing to that directory, because then it would be easy for anyone, including us, to have them just work by copying the correct UI scenes into `demo/ui`. It will certainly make it easier for us to test functionality and Godot has a functional interface for sorting out dependencies, so I think it probably won't be too difficult to copy the files into `game/ui` or `whatever/ui` either?

**Comment by mjtorn** [comment]
Half a year after commenting on this subject, it has become relevant again. I couldn't help but notice from `git log` that inventory is expected to live under `hud_layer/hud` but with an external setting it doesn't. PR #80 was a tough one and we had other problems at the time, so I'm forced to revisit this again.

I will strive to have an implementation that considers the inventory a part of the HUD, as in `hud_layer/hud` but doesn't break the demo game, Iron Sky: A Lunar Adventure or the upcoming game Iron Sky: Cold War.

**Comment by StraToN** [comment]
Not relevant anymore with Escoria rewrite. 
ALL UI-related scenes are the gamedev's task. It just has to call Escoria API when needed.
