### ISSUE TITLE
Escoria Logo

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#101]
Hello everyone!
It is time for Escoria to have a proper logo. To refresh our mind of all these bugfixes, I propose to have a look at the proposals of Livio Fania (www.liviofania.com).
![escoria](https://user-images.githubusercontent.com/1289207/38012217-d6969d28-3260-11e8-86ff-af442ea8464c.jpg)
![rect1346](https://user-images.githubusercontent.com/1289207/38012218-d6b43eb4-3260-11e8-960d-766b69d4ddab.png)
![rect1368](https://user-images.githubusercontent.com/1289207/38012219-d6cdc780-3260-11e8-918a-c3fcf511c7a2.png)
![rect11244](https://user-images.githubusercontent.com/1289207/38012220-d6e52c4a-3260-11e8-8411-1e7c15ed84ba.png)

Edit: I modified this logo to set it in blue and take your remaks into account.
![escoria-blue](https://user-images.githubusercontent.com/1289207/38166448-52c9e38a-3524-11e8-9b4a-65f00a3d2daf.png)

We also have a proposal from ghost in #5 
![image](https://user-images.githubusercontent.com/1289207/38012363-89317304-3261-11e8-9840-b7254867ac3b.png)

I'll also update this post with other proposals if we receive more later.

**Comment by mjtorn** [comment]
My first reaction to the first logo was "It looks like someone flipping the middle finger" :( It's a great concept, but if the middle thing was shorter and the two outer things longer, it would not look like flipping someone off. If anything, it would look heavy metal :metal: which I whole-heartedly approve of ;)

The others could be refined further, but the first one, apart from the above, feels like the most complete logo!

**Comment by fleskesvor** [comment]
Wow, those are some great concepts. I think my favorites are the first and last ones.

Maybe the first should have had a Godot-esque blue color instead of the green ScummVM color, but that might not be a good fit with the green loogie. If the loogie was a little twisted, it would probably look less like a hand.

I think the last one would look better with the magnifying glass between or on top of the adjacent letters. It could also be a good fit with something like ghost's icon, but I think that needs a larger magnifying glass and sharper outlines.

**Comment by lavaduderDev** [comment]
I like the last one. The Godot robot is present, which is friendly sight to the eye (Makes me smile.). Though it needs more "ADVENTURE AWAITS", presentation. Like a pose that displays what Escoria is like.

I like the magnifying glass of the second logo. But it really doesn't have any sort attachment like the last one. Though I personally feel this is the most refined logo of the 3.

Like fleskesvor was saying, the first one should have Godot Blue. It's clashing, and brings out a sort of puke look, It's nasty.

**Comment by fleskesvor** [comment]
To clarify, when I wrote the last one, I meant the last one from Livio Fania. I think ghost's icon was added in later, so it got a bit confusing. I do also like that one, but it's a bit rough, and I think it would be a good idea if there's both a large logo and small icon and they share style and some elements, eg. the loogie or a magnifying glass.

**Comment by StraToN** [comment]
Edit: added a modified proposal.

**Comment by fleskesvor** [comment]
> Edit: added a modified proposal.

What changed?

**Comment by StraToN** [comment]
@fleskesvor I added a blue version of the 1st green logo.

**Comment by fleskesvor** [comment]
Thanks, @StraToN.

Looking at it though, I think it seems a bit off with the loogie in blue, and I think I prefer the original green version. Or maybe a blue version with the Godot icon as the 'o' would look good? Or maybe with the magnifying glass instead, and having that same magnifying glass in an improved version of ghost's icon suggestion as well.

**Comment by lavaduderDev** [comment]
I like-ish the blue change of the 1st one. Once again I agree with fleskesvor, the spitball has got to go. I'd say put an improved version of the Godot Robot on there (With an Indiana Jones' grin.) I also think the blue gradient is too dark/saturated.

**Comment by fleskesvor** [comment]
It's not that I think the spitball doesn't have a place in the logo—in fact, I think it's a fitting reference to both the Escoria name and the LEC classics—I just haven't been completely sold on the implementations yet. I wonder how it would look if the spitball was traveling left and replaced the 'E' instead of the 'O'. The 'O' could then be a variation on the Godot icon (or a magnifying glass), but that might be a bit much. There's probably a nice balance in having the icon be in the middle of the logo too.

**Comment by Beuc** [comment]
As far as I'm concerned I'm for the first logo. Is has solid look&feel, it has a distinctive shape and can easily be used as an icon (e.g. for the Godot Asset Library). Not another remix of the Godot logo plz ;) Also Livio Fania is a professional artist proficient with free/open source software (e.g. [featured at Krita](https://krita.org/en/item/interview-with-livio-fania/)), it's the kind of contribution we want to see more often :)
