### ISSUE TITLE
use of the escoria script from the regular gdscript side?

### ISSUE THREAD

**Issue by ghost** [godotengine/escoria#11]
the escoria script is nice and quick, but sometime they are not enough for unusual uses. For example it would be nice to have a clean way to use the "change_scene" without use the restricted .esm files (regular GDScript).

Is this possible? I didn't find any guide/reference.. and also I am asking around; but still unable to figure it out.

**Comment by StraToN** [comment]
The ``change_scene`` function is defined in the ``https://github.com/godotengine/escoria/blob/33139f2c47b29a04602d2d2b64c9f5fc726a9acf/device/globals/global_vm.gd#L433`` file. 

This file is the actual "virtual machine' that deals with instructions sent through *.esc files (not *.esm, btw). It is defined in a real node in the base global scene ``global/scene.scn``.
You will have to manage direct calls to this VM node in order to make your call. This kind of invalidates the whole essence of the framework though, which aims at enabling game designers to write their game as a scenario (like a movie), not through script code.

**Comment by StraToN** [comment]
Using GDscript is not currently possible in Escoria rewrite. We'll add this to the TODO list.
