### ISSUE TITLE
Configurable keyboard bindings

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#125]
Currently `Escape` and `Tab` have hard-coded meanings, which aren't documented anywhere.

Escape opens the menu and Tab opens the inventory. These are good field-tested shortcuts, but there are cases where they don't necessarily apply, for example:

  * Preferring `i` to open the inventory
  * Owning a Razer gaming keypad which doesn't have an Esc key and doesn't allow key remapping in Linux

For AdventureJam2018 purposes it might be enough for participants to document them in-game and have this on a low priority to be fixed after the Jam.

**Comment by fleskesvor** [comment]
Yes, this needs improvement and documentation. We shouldn't hardwire these keyboard shortcuts to specific buttons at all, but instead use custom actions, like `menu_toggle` and `inventory_toggle` and configure these to a few common defaults. We should also eventually create the missing menu templates (settings, save/load and credits), so that it will be possible for a user to easily re-map the key bindings.

**Comment by StraToN** [comment]
Very good idea. This would allow multiple shortcuts for each purpose (see Deponia games, smartly using mousewheel down to expand the inventory and mousewheel up to collapse it).

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
