### ISSUE TITLE
Dialog options not working?

### ISSUE THREAD

**Issue by lavaduderDev** [godotengine/escoria#13]
I have had a lot of issues trying to get the multi-choice dialog box working. the background shows up, but not the buttons/text.  I don't know why it isn't working.
```

:look

say player "I have several things to say about this can"
?
	-"Yes"
		say player "Yes"
	-"Very much yes"
		say player "Very much yes"
	-"There is not a lot to say about it actually"
		say player "There is not a lot to say about it actually"

```

for the entire project (Incase the bug is deeper than the escoria script.) click this link
https://github.com/lavaduderDev/Glitchedupescoria

**Comment by StraToN** [comment]
As answer on QA, you forgot to add a space between the "-" character and the according dialog option.
```
:pick_up

set_global i/inv_can true
set_active can false


:look

say player "I have several things to say about this can"
?
	- "Yes"
		say player "Yes"
	- "Very much yes"
		say player "Very much yes"
	- "There is not a lot to say about it actually"
		say player "There is not a lot to say about it actually"
```

**Comment by lavaduderDev** [comment]
Thank you! This was the exact problem I had. You can close the issue.

**Comment by akien-mga** [comment]
Should the parser be made more forgiving?

**Comment by StraToN** [comment]
Well, to be fair I didn't think this was the cause of the problem. I just looked at the flossmanuals page regarding dialogs and saw that there was a space there. However, I just threw a glimpse at esc_compile.gd and didn't see any specific command concerning that space presence or not. I'll have to investigate further.

I don't see any reason not to have this fixed though, indeed. Let's ask @punto- if that was intended.

**Comment by punto-** [comment]
the space makes sense, lines in esc are interpreted as words separated by spaces (although a word can contain spaces if it's in quotes). The first word ‎of the line is the command, which in this case is "-", the command for the dialog options (at least in theory; dialog options are actually handled as special cases and not as normal lines, but I like to make them follow the same rules as all other lines to keep consistency, that's why they changed from the old format which started with "*")I'm not opposed to re-implementing esc_compile.esc as a proper lexer since right now it's a mess, but I don't  think it's a huge deal to require that space.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Julian MurgiaSent: Tuesday, April 18, 2017 2:19 AMTo: godotengine/escoriaReply To: godotengine/escoriaCc: punto-; MentionSubject: Re: [godotengine/escoria] Dialog options not working? (#13)Well, to be fair I didn't think this was the cause of the problem. I just looked at the flossmanuals page regarding dialogs and saw that there was a space there. However, I just threw a glimpse at esc_compile.gd and didn't see any specific command concerning that space presence or not. I'll have to investigate further.
I don't see any reason not to have this fixed though, indeed. Let's ask @punto- if that was intended.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/godotengine/escoria","title":"godotengine/escoria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/godotengine/escoria"}},"updates":{"snippets":[{"icon":"PERSON","message":"@StraToN in #13: Well, to be fair I didn't think this was the cause of the problem. I just looked at the flossmanuals page regarding dialogs and saw that there was a space there. However, I just threw a glimpse at esc_compile.gd and didn't see any specific command concerning that space presence or not. I'll have to investigate further.\r\n\r\nI don't see any reason not to have this fixed though, indeed. Let's ask @punto- if that was intended."}],"action":{"name":"View Issue","url":"https://github.com/godotengine/escoria/issues/13#issuecomment-294684259"}}}
