### ISSUE TITLE
Make blocking version of camera_set_target

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#144]
As discussed in #111, using `camera_set_target` does not block execution of events, unlike `say`, `change_scene` and several other esc functions. This results in surprises with multiple consecutive calls to `camera_set_target`, since each new call will interfere with the previous. The issue can be mitigated somewhat with `wait`, but since `camera_set_target` does not block, `wait` will be executed immediately, so to achieve the desired result with camera movement, one must make sure that the wait time is longer than the time it will take the camera to reach its destination before the next call.

**Comment by mjtorn** [comment]
How would this be achieved? The `camera_set_target` function is very different from `wait` in its structure, as the bulk of the work is done in `update_camera`... And there are legit reasons for updating the camera position without blocking, I believe.

**Comment by fleskesvor** [comment]
> And there are legit reasons for updating the camera position without blocking, I believe.

That's a good point. Maybe our only option is better documentation, and maybe write to output how many seconds it will take to move the camera to the desired position as a help to the developer and/or add an option to use `camera_set_target` with seconds to reach target instead of speed.

**Comment by mjtorn** [comment]
Not sure I see where the "how many seconds" output would be printed. I did think that a measuring tool would be useful, or something else that calculates a distance between two nodes or points, but that'd have to be integrated into the UI and relates to making Escoria an asset and is generally overkill.

`walk` has a counterpart `walk_block`, so I think `camera_set_target_block` would be a good idea despite its verbosity. And we could stick to a speed measured in px/s for now to not break anything.

The hard part is that the camera update would have to be tied into the state of the vm, so that execution of the ESC stack is blocked for anything except `camera_set_target_block`.

**Comment by fleskesvor** [comment]
> `walk` has a counterpart `walk_block`, so I think `camera_set_target_block` would be a good idea despite its verbosity. And we could stick to a speed measured in px/s for now to not break anything.

Yes, I agree. This sounds like the best possible solution.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
