### ISSUE TITLE
Rework item.gd and item_background.gd to avoid duplicated code

### ISSUE THREAD

**Issue by StraToN** [godotengine/escoria#16]
These 2 scripts duplicate code, that is bad. We should simplify using an item_base.gd script to be extended by item_background.gd.

**Comment by punto-** [comment]
If I remember correctly item.gd already inherits from interactive.gd,
player could probably inherit that too

**Comment by StraToN** [comment]
@punto- Yes, that would be an improvement, indeed, and it would help for #14 too.

**Comment by fleskesvor** [comment]
If item_background.gd was made to extend item.gd instead of interactive.gd directly, it could be cleanly cut down to the following short script:

https://github.com/fleskesvor/escoria/blob/unify_interactive_scripts/device/globals/item_background.gd

The `_ready()` function is so short because the `_ready()` function of the extended script is automatically called, though this might apparently be subject to change in 3.0, so maybe it's best to add an explicit call with `._ready()`.

**Comment by punto-** [comment]
I don't think it should extend it, it's like 3 lines of code, you can put
them in item.gd.. just check the type of "area" and connect the input
signal to a different callback, that should be enough shouldn't it?

**Comment by fleskesvor** [comment]
I'm not sure. Items use Control nodes for input, while item_backgrounds use Areas, so the input functions have different signatures. Can that be solved with overloading, or alternatively by giving viewport and shape_idx default values, in case the input node is a Control?

**Comment by punto-** [comment]
Yeah, you connect both input signals to different functions, but both
functions end up calling the current input function, with the input event.
The viewport and shape are not used at the moment anyway.

**Comment by fleskesvor** [comment]
Yes, I connected both input signals in a [new version of item.gd](https://github.com/fleskesvor/escoria/blob/unify_interactive_scripts/device/globals/item.gd) and that works nicely. The `is_type()` check should perhaps be on CollisionObject2D instead to be accurate, but I don't know if it will ever be desirable to use a PhysicsBody2D as an item.
