### ISSUE TITLE
Single place for dialog player

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#199]
The way I got it from #180 and #198 it would make sense to place the dialog player in a single place, instead of every possible game.gd derivative. The dialog player contains a `PackedScene` which must be adapted for every game, and the script that manages it.

A counter-argument could be that if a game uses tons of different game.gd-style scripts in different rooms, the dialog player should not be moved.

Is it a valid counter to that counter-argument to say that whatever you want, you can do with dialog types?

----

What needs to be coded for #180 to come back is some kind of ratio adjustment between the room size and the visible viewport.

**Comment by fleskesvor** [comment]
I think #180 was more or less right about where to place it, but it had issues with positioning because of the missing ratio adjustment you mention.

A fix should revert the recently merged #202 before addressing these issues.

> A counter-argument could be that if a game uses tons of different game.gd-style scripts in different rooms, the dialog player should not be moved.

> Is it a valid counter to that counter-argument to say that whatever you want, you can do with dialog types?

I'm not sure what kind of scripts you have in mind, but if a developer needs multiple kinds of dialog, they're better off adding multiple dialog scenes to the dialog player with different styles, offsets, margins, etc. and referencing them explicitly with the `say` command.

**Comment by StraToN** [comment]
Not relevant anymore in Escoria rewrite. Dialogs are now placed in their own folder (set by gamedev, not by Escoria) and this folder is set in the Project Settings. DialogPlayer scene then automatically loads the needed scenes.
