### ISSUE TITLE
Improve test scene

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#22]
I was browsing the AGS forums the other day, when I came across this [topic about Escoria](https://www.adventuregamestudio.co.uk/forums/index.php?topic=54025.0)

One person notes that:

> The bare-bones example it comes with is... rough. And buggy, **very** buggy

Unfortunately, this is still true. I've experimented quite a bit with the framework these last few weeks, and I've come across several rough spots.

To make Escoria a more attractive alternative to AGS and proprietary engines like Visionaire Studio and Unity3D + the Adventure Creator plugin, I think some improvements are in order, to give a better first-impression of this framework.

Some issues/suggestions:
* [x] "New Game" and "Quit" buttons in main menu don't work (see #23)
* [x] Use an Area2D as background with the script from b750a4a882b8594ab58c729baad3307704c19edd, since it's more flexible
* [x] Improve project structure for the test scene—eg. scenes/rooms/test/, scenes/characters/player/, etc. to teach users to re-use scenes and assets—instead of lumping everything together in scenes/test
* [ ] Add examples of using separate dialogue scenes per character (font, color, size etc.)
* [ ] Add examples of implementing cutscenes
* [ ] Add examples of changing "rooms"
* [ ] Ease translations files management (cf #27 )
* ++?

Don't get me wrong—I really like Escoria! And since it's so easy to utilize everything Godot has to offer, it's a very powerful framework that I hope gains more popularity. I just think it needs a bit more polish.

**Comment by StraToN** [comment]
I agree with all this. 

I propose we design a new example set of scenes that makes use of all Escoria features. These features don't have to be thrown in one big scene (as this will be harder to understand & maintain).
This issue seems to be a good place to go.

Here's my idea ( @fleskesvor  this is what we talked a few time ago): **mimic** The Secret of Monkey Island's introduction. We don't want to rip the assets, only the scenes' architecture. This goes from the title scene to the outside of the SCUMM bar. 

1. SCENE 1 : Title
Simply the logo with credits. I'm not sure this is really useful, but we could also run it at another moment, such as at the end of Scene 2.

2. SCENE 2 : cutsene + dialog
a. cutscene : the actor enters, looks around and speaks with an NPC (no real dialog interaction with player). At the end of dialog, the player moves out of the scene
b. if the player goes back to this scene, he triggers a dialog (a real one)

3. SCENE 3 : outside (large width)
Goal: use of camera2D to follow the actor as he walks through this large scene
- Some objects to see in the background (background_item)
- Some objects to pick (inventory)

**Comment by fleskesvor** [comment]
That sounds like a great idea! Looking at the list of commands in esc_compile.gd, I think that should make room for most/all of them. I feel like scene transitions, camera, animations, dialogue trees, verbs and inventory are the big ones, but there are also features I'm not familiar with at all.

**Comment by punto-** [comment]
The first thing I would say is remember the first paragraph of the book,
we're not really trying to compete with these "complete solution" packages
like the ones mentioned on that post.. So I'm not that worried about that
kind of thing, we're different from that.

But obviously I like improving the demos, so I'm happy with this.

**Comment by StraToN** [comment]
@punto- Sure, we are not trying to bypass the essence of Escoria, not at all :)

Only assessing that a good demo for it fill 2 goals: 1/ Demonstrate the framework and as many of its capabilities as possible, obviously, and 2/ Attract users with a good-looking example. 

Some users often wrongly believe the demos demonstrate the full capabilities of a framework or an engine (esp. looking at graphics). In the case of Escoria, there is no such thing because that's for adventure games. However, I'd just love having a nice and beautiful example bundled with Escoria.

**Comment by punto-** [comment]
yeah that sounds great, I'm all for it

**Comment by fleskesvor** [comment]
@punto- I understand that from Escoria's perspective, there's no need to compete with any of those "complete solution" packages. (I have read your presentation from Respawn 2015.) What I meant is that from a developer's perspective, I would like for Escoria to be seen as an attractive alternative to those solutions. I'm not a game developer myself, but I love adventure games and FLOSS, and I'd like to see more actual game developers use an engine and a framework founded on that ideology, where there's also first-rate support for Linux; including the editor.

**Comment by StraToN** [comment]
Also, just to add a small note about flossmanualsfr's small project "Escoria in Daïza" (EiD): even though it is a great example for learning the same stuff we want, I think this should stay a side-project for multiple reasons.

1. I am personally not fond of the graphics style, but I do recognize its huge quality. I know it is voluntarily drawn to be childish, but after all these years passed on LucasArts games, my personal preference goes to human playable characters (with the notable exception of Sam & Max).
2. It misses long cutscenes involving dialogs and animations. The kind of cutscenes that players see as a reward for their efforts, y'know :)
3. Inventory is just a container in EiD, and it doesn't feature items combinations. Too bad, I'd love to show a simple example for each item combination possibility.
4. I think it is interesting to propose another presentation of the GUI (to be determined) than the one proposed by EiD: in comparison, EiD works with kind of verbs buttons. I'd be glad to work on another functionment, close to what The Dig did (left-click = primary action / right-click = look). Usually, when you click a pickable object, the player walks towards it, says something before picking it (not mandatory), then takes it.
5. Finally, we also need to master the framework better too. I'd be happy to discover it fully without simply following the (great) tutorial they wrote, but use it as a reference. That's what I personally do ;)

**Comment by zero2000** [comment]
Hello, they know, have used renpy, is to make visual novels is very popular, also should add features of this to scoria. Should see that course to be able to do something stein gate style

**Comment by zero2000** [comment]
Maybe I do not express myself well, but for them to have an idea should see as it is stein gate or the games of the person saga especially the 3 4 and 5 they make a very good game and maybe if they see since in youtube there are People who play those and in the case of person combines point and click parts and rpg, in the case of stein gate combines very well the change of time image of the upper left is the days anted that the character back or forward and those things Must see them to integrate them into escoria, to evolve

**Comment by StraToN** [comment]
@zero2000 I understand you request a new feature to integrate RPG elements in Escoria. This is a good idea, but please open a new issue instead of using an existing one. We are talking about the demo scene here.

**Comment by fleskesvor** [comment]
Not strictly related to the test scene, but it might be a good idea to add a list of features that are supported "out of the box" to the readme, since that's a thing people are going to be looking at when deciding between Escoria and any of the alternatives. Things like eg. scriptable actions and dialogues, verb bar/"coin", customizable UI, etc.

And if the test scene gets in a better shape, it might also be an idea to provide pre-built binaries for at least Linux, Windows and Android so that it's more accessible to potential users who are looking around for alternatives, and might not want to go to the effort of downloading the editor just to check out the possibilities.

**Comment by StraToN** [comment]
Not relevant for escoria rewrite as new demo scenes are now included.
