### ISSUE TITLE
Opinionated Tutorial and Video

### ISSUE THREAD

**Issue by sjb8100** [godotengine/escoria#248]
I was looking at using escoria for a 3D use case. I searched the repo for "tutorial" and did not find anything official. As a new comer and possible (likely) contributor to escoria it is essential to have a tutorial prefer video companion to quickly get new comers up to speed with what a common opinionated escoria approach should be esp. how one might use the scripting language for 3D https://github.com/godotengine/escoria/issues/44

**Comment by mjtorn** [comment]
First a shameless plug: coming from Finland, we have maybe the worst crowdfunding laws on the planet, so there's no way to run a campaign to fund this kind of stuff. I have suggested to @StraToN that our company could be contracted to make a tutorial game and videos, if someone manages to raise the funds first. Please see https://ironsky.game/ for games. The Cold War demo isn't out yet, but will be soon, and it's vastly superior to A Lunar Adventure.

Wanna take a shot at Kickstarting something?

------

The scripting language does not deal with 3D at all, but some improvement ideas have been tossed around for adding keyword arguments to the scripting language, which might make it easier to add a third dimension to some calls.

On the other hand, Godot 3.1 (allegedly, I've heard) is stricter about what types of nodes scripts can be attached to, so that might be a challenge.

**Comment by StraToN** [comment]
Hello,

Escoria is not fit for 3D at the moment, sorry. This may happen in the future but don't expect it anytime soon.
You may want to look at GOAT project instead https://github.com/miskatonicstudio/goat/tree/master/.
