### ISSUE TITLE
Errors running Escoria in Daïza tutorial

### ISSUE THREAD

**Issue by giuliosoro** [godotengine/escoria#259]
Hi, following line by line the Escoria in Daïza tutorial with Escoria3 I fail to run even on the first scene ( https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/creat-your-scene/ ) , with AssertionFailed: "Errors in File item, Background item area is not Area2D"

![schermata 2019-01-06 alle 14 40 55](https://user-images.githubusercontent.com/46420138/50737015-d701ea80-11c4-11e9-85e9-bfbf35063807.png)

**Comment by mjtorn** [comment]
@giuliosoro sorry, but that's a bit outdated. Please refer to docs/items.md for the up-to-date item documentation.

Note that it only calls for `Control` objects in conjunction with parallax backgrounds. This may change soon, I hope, because those types of objects should really only be used for UI elements.

Using `TextureRect` or something in inventory items should work, and it's kind of a UI element, but on the other hand there's PR #258 which may remove that. In theory, if I have time for it, I would like to have inventory items be more like regular items, and the code would set the z-index to the maximum z-index possible, and there would be no more special cases. This would need a sign-off from @StraToN and I hope he'd be fine with it, because magic removal was a bit of a theme in 2018.

**Comment by j2l** [comment]
I have the same problem.
I discovered Escoria through fr.flossmanuals.net Daïza tutorial and failed making it at first scene.
Would it be possible to update this ticket with steps to make it work?

**Comment by Beuc** [comment]
FYI, while Escoria 3.x is underway, Escoria 2 was ported to Godot 3.2 (branch esc2-godot3.2) and the Escoria in Daïza was updated for Godot 3.2 as well :)
