### ISSUE TITLE
Problem: Tooltips not working or not showing up

### ISSUE THREAD

**Issue by ruperstinsky** [godotengine/escoria#261]
I'm absolutely new to this framework, but I love the genre and the idea behind Escoria, now I guess everyone knows the Floss tutorial for the 2.1 version. So I'm trying that one but in the newest version, everything is fine except a little big problem, I cannot manage to make the Tooltip work, I've tried probably 8 different times, everything works, the output window tells me that it's sending the signals (mouse_enter, mouse_exit), but the "tooltip" name or anything for that matter shows in the tooltip box. I'm getting very frustrated and there's basically zero tutorials apart from the manual that is outdated. 
The most probable thing is that I'm doing something wrong or forgetting to check-uncheck a box in the item's inspector. I'd love to use the Escoria framework for a project. I'll thank anyone who can help this poor soul.

**Comment by akien-mga** [comment]
I'd suggest to retitle your issue to actually focus on what your question is, and not a judgement on its pertinence.

**Comment by pinellos** [comment]
i've the same issue... tooltips seems broken... please help

**Comment by mjtorn** [comment]
Please pull the latest code. I committed cfac9cd with some fixings.

Sadly this is the dark side of open source; the demo rooms are a mess, there's some work going on to get new demo rooms, and some bugs remain because our games use a custom HUD, so it's easy to neglect testing the demo stuff.

At the risk of sounding like a broken record, but this comes up a lot. Like every other open-source project, the incentives are a bit skewed. We as a small studio need to make our games and hope to make money one day. Escoria is just a tool, one that has required almost as much work as writing something from scratch on another engine. Therefore we (or someone else) would need proper funding to get demos for every feature, and as an incentive to make sure things work.

I've been trying to offer money to fix some Godot-level bugs that make Escoria difficult to deal with, but no one's been interested. Maybe you'll have better luck setting up a crowdfunding campaign for Escoria demos. Can't do it myself, because of time and legislation constraints, but our company would be happy to take on the work, just not for free.

Hope the commit helps, though.

**Comment by mjtorn** [comment]
@ruperstinsky and @pinellos is this still a problem for you?

**Comment by fleskesvor** [comment]
I'm closing this issue since it was presumably resolved by cfac9cd42f57e94f65d94d5831ffb25ee4d7f41a. Feel free to re-open it if you're still experiencing this issue, @ruperstinsky.
