### ISSUE TITLE
Get multiple errors on Godot 3.1 and 3.1.1

### ISSUE THREAD

**Issue by Alyks** [godotengine/escoria#267]
Would you know when an official support for Godot 3.1.1 will be available? I hope there is a project to port it to recent version. I've tried Escoria 3.0 on Godot 3.1 and 3.1.1 but there's multiple errors on files before i can play with it and impossible to run a preview of the Daïza game from IDE.  I understand that the latest version of Escoria is only tested on Godot 3.0 and i've already seen this thread **[#237](https://github.com/godotengine/escoria/issues/237)** about similar issue on Godot 3.1.

**Comment by mjtorn** [comment]
I had to revert our current development back to 3.0, because the Spine module caused a segfault every time the game was quit. This is why the 3.0 branch is more active than 3.1/master, as @StraToN cherry-picks the changes when he can.

The Daïza game is completely unsupported at the moment, as no one has the time or money (you could pay me or my company if you want; let me know and we can set something up) to bring it up to speed. IIRC it also has some worst practices, like using `Control` nodes for game elements.

Using `Control` should be banned entirely. There are corner-cases, like having an always-open non-blocking inventory, which currently pretty much has to be `Control`-based, making it impossible to animate an inventory item.

Likewise it would be nice to see if the action menu could be `Node2D`-based, because with a tooltip that follows the mouse, you will see the tooltip after selecting an action (until you move the mouse), because `Control` captures mouse movement and therefore doesn't see that the mouse exited the item while moving to the action button.

Either way, you might want to look at the demo rooms provided in the 3.1 branch.

You can also cherry-pick commits from the 3.0 branch and if they work for you, make PRs to pull them into 3.1. I doubt there'd be much bureaucracy around the matter if you see that everything works.

I should probably drop a quick comment on the issue you mentioned as well...

And, as always, unfortunately too busy struggling with our own studio's business to do pro-bono work for old tutorials. I wish it wasn't so, but incomes and expenses need to be balanced, and paid contract gigs to update them would help a lot.

**Comment by Alyks** [comment]
I completely understand.  Thank you for your explanation. I was a bit lost and now this help me make decisions on my current projects.

**Comment by jeancallisti** [comment]
Hello! For the record, for the last few years my (tiny) team and I have been developing a full-length point-n-click game with AGS (still in progress) and I'm considering scaling up to a better engine, like Godot-Escoria. If that can be an incentive to make Escoria fully compatible with Godot 3.1.1... this is just a shot in the dark.

**Comment by mjtorn** [comment]
@jeancallisti what kind of problems are you seeing? In the spirit of open source, you can try fixing them yourself. AFAIK the biggest, or maybe only major, problem _we_ have had is the shitty Spine support, which keeps us on 3.0.

I'm not very familiar with AGS, so correct me if I'm wrong, but it doesn't do advanced character shadows and such, or does it? In that case you should also be fine with 3.0.

**Comment by jeancallisti** [comment]
I'm not engineering issues myself as I haven't been using Escoria yet. I'm referring to the issues described in this very thread.
I'm ok to use Godot 3.0, I'm just weary of starting to use a piece of software which development has stopped even before I start using it.

**Comment by mjtorn** [comment]
@jeancallisti the tooltip-after-action-menu bug has been fixed in the 3.0 branch, I don't know if @StraToN has cherry-picked it. Otherwise it seems that many issues stem from working with the Daïza tutorial, which is sadly defunct as it is.

The 3.0 branch is what we're currently using and I don't think we have any bugs related to how you'd use Escoria, only crappy Spine support.

As a disclaimer I must say I haven't tested the always-open inventory situation in our other game, to see if it can be made `Node2D`, but still, animated inventory items can be considered an exotic corner case for all I (currently) care...

**Comment by jeancallisti** [comment]
That's great, thank you for the answer

**Comment by Beuc** [comment]
FYI, while Escoria 3.x is underway, Escoria 2 was ported to Godot 3.2 (branch esc2-godot3.2) and the Escoria in Daïza tutorial game was updated for Godot 3.2 as well :)

**Comment by fleskesvor** [comment]
I tested Escoria with the current stable version of Godot (v3.2.3) yesterday, and didn't encounter any problems. Daïza can also be played through without errors by cherry picking 74edead092f05afdf38339376d7f120fbadeb18d, so I'm closing this issue, and will open a PR on that project as soon as possible.
