### ISSUE TITLE
Tool tip does not work when using items

### ISSUE THREAD

**Issue by lavaduderDev** [godotengine/escoria#27]
Instead of combineitem, and item-that's-being-combined. It says "combine_id"/"id"

say I use a icecream cone on bob. instead of it saying "use icecream bob" It says use.combine_id

The issue is in game.gd
lines 31, 38 and 49.

**Comment by fleskesvor** [comment]
The issue is that a translation file is provided (translations/general.csv), but it's not imported into the project by default.

From the top left menu in Godot, select Import -> Translation, enter the path to translations/general.csv in the "Source CSV" field, select a "Target Path" and press "Import".

You should now see the proper text strings in-game as provided by general.csv.

I agree that this isn't particularly intuitive, and it's probably a good candidate for the list of improvements in #22.

**Comment by StraToN** [comment]
Following in #22
