### ISSUE TITLE
Parser Error: Variable "i" already defined in the scope (at line 39)

### ISSUE THREAD

**Issue by matthewedogawa** [godotengine/escoria#285]
I am pretty new to godot and am trying to create a point and click game, but after opening the project.godot file, I looked at the scene_main script and ran everything only to get:
error(94, 7): Variable "i" already defined in the scope (at line 39)

Am I doing something wrong or is there a different version I should be looking at.  Also, while I'm here I was wondering if it was possible to also add a turn-based rpg aspect if I learned from references such as: https://www.youtube.com/watch?v=nskVFc3tJgY or https://www.youtube.com/watch?v=FV4JkwI4OF4&list=PLhqJJNjsQ7KHaAQcGij5SmOPpFjrDTHUq&index=3
Sorry if this isn't the place to ask the second part.  I am just wondering.

**Comment by Vikram1323** [comment]
> I am pretty new to godot and am trying to create a point and click game, but after opening the project.godot file, I looked at the scene_main script and ran everything only to get:
error(94, 7): Variable "i" already defined in the scope (at line 39)

Please tell:
- Godot Version
- Escoria Version
- Error from Godot's Debbugger

> Am I doing something wrong or is there a different version I should be looking at.

Escoria 2.0 is stable and Escoria 3.0 is under maintainance.

>Also, while I'm here I was wondering if it was possible to also add a turn-based rpg aspect if I learned from references such as: https://www.youtube.com/watch?v=nskVFc3tJgY or https://www.youtube.com/watch?v=FV4JkwI4OF4&list=PLhqJJNjsQ7KHaAQcGij5SmOPpFjrDTHUq&index=3

In theory Yes.

>Sorry if this isn't the place to ask the second part. I am just wondering.
IMHO, You can ask this question here but It is better to  ask one question at a time unless they one don't make any sense without the other.

**Comment by Vikram1323** [comment]
Change i to k  (line 94, 95)
`for k in range(avatars.get_child_count()):
      var c = avatars.get_child(k)`
res://globals/dialog_dialog.gd

Then run you will get error again 
Parser Error: A value of type "self" will never be an instance of "Area2D".
Comment line 90 of res://globals/trigger.gd

`line 90 # assert(self is Areas2D)`

**Comment by matthewedogawa** [comment]
Thanks for the advice.  I made the changes and got the demo to work now I am just going to be searching for how to implement everything I want.  Do you have any advice for a better place to find info and ask questions?

**Comment by Vikram1323** [comment]
For Escoria and Godot read this (maybe you know this already)
- https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/what-is-point-and-click-games/
- https://github.com/godotengine/escoria/tree/master/docs
- https://docs.godotengine.org/en/stable/

There are not a lot of Escoria user's because it is under a lot of changes (https://www.youtube.com/watch?v=K76PzOgpyjk) So you may get a little frustrated. If you are new to Godot or programming in general, I would say read more and watch less. 

Better place to ask questions?
To be honest there is no perfect place.
You can make issue like you did or try something from here https://godotengine.org/community if you don't receive answer in 1 or 2 days.

Enjoy:)

**Comment by matthewedogawa** [comment]
Thank you for everything :).
