### ISSUE TITLE
Need of "actions" node in inventory, missing part in Escoria's documentation

### ISSUE THREAD

**Issue by Kubees** [godotengine/escoria#29]
**Hello once again!**

   Today, I was going through inventory system, I followed everything as it is written [here in Inventory chapter](https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/inventory/), but it seems, that it is missing a word about node of Control type called "actions".

   Before adding this node into inventory scene, I was experiencing unsuccesful attempt to call function get_child_count in inventory.gd, then I checked basic inventory setup, which comes with _Escoria_, and there it was. After adding, no problem. Please, for another new users, update documentation. There is written, you have to include those arrows for going through items, which I don't need, but it is there, so I added them and it works. This should be included too.

   By the way, what is that "actions" node used for? Is it used while using items from your inventory? Thank you for your response, sir!

**Comment by fleskesvor** [comment]
Yeah, there's some discussion about improving the test scene in #22. The framework is more confusing than it needs to be, both because of such issues and because there several nice features in Escoria that are not even used in the test scene.

Which action node are you referring to? I couldn't find that, but there's the action_menu scene which can be used to create verb coin interfaces, like the one in Full Throttle, and the action variable, which is exported by the item script, which is used for one-click interfaces, like in many point-and-clicks from recent years.

**Comment by Kubees** [comment]
I am not refering to  action_menu scene, I am refering to inventory scene. When I am building my own custom inventory scene, it has to have empty node called "actions" of Control type, else it won't run. There is nothing written about it in documentation, but that "actions" node is actually included in sample project, that comes with Escoria.

**Comment by fleskesvor** [comment]
Oh, I see. Looking at the code in `inventory.gd`, I don't think that node serves any purpose at all, but the script makes the assumption that it will be there, hence it fails if it isn't.

Declaration of `actions` array:

    var actions = []

Signal handler:

    func action_pressed(n):
        current_action = n
        for but in actions:
            but.set_pressed(but.get_name() == n)

Connecting signal in `_ready()`:

    var acts = get_node("actions")
    actions = []
    for i in range(acts.get_child_count()):
        var c = acts.get_child(i)
        actions.puah_back(c)
        c.connect("pressed", self, "action_pressed", [c.get_name()])

Presumably `acts.get_child_count()` fails, since `acts` is not defined. Also, `puah_back()` is misspelled, and not an actual function of the `Array` object, but execution never gets that far.

I think this is code that was refactored into the separate `action_menu.tscn`, as `action_menu.gd` has a similar implementation, but one that actually works.

**Comment by Kubees** [comment]
Oh, okay. I was wondering, what type of action could an inventory system have. Thank you.
