### ISSUE TITLE
Hide left/right inventory arrows when nothing to navigate to

### ISSUE THREAD

**Issue by OddHouseGames** [godotengine/escoria#294]
Is it possible to hide the left and right arrows in the inventory when there is nothing for it to switch to? They are still clickable but not needed in that scenario.

**Comment by StraToN** [comment]
Hello,

Escoria is currently in the process of being rewritten for a big part of it, while keeping some of its components unchanged, such as ESC scripting languages.

For the inventory part, it is already rewritten in a way that Escoria only manages the list of what is or is not in the inventory. The UI part will therefore *not* be managed by Escoria at all, so that *you*, the game developer, are able to make it react the way you design.

For the moment, you'll want to edit function sort_items() function at https://github.com/godotengine/escoria/blob/74edead092f05afdf38339376d7f120fbadeb18d/device/globals/inventory.gd#L96 so that it manages the visibility of nodes "arrow_prev" and "arrow_next" (if they exist), depending on the number of pages and the current page.
