### ISSUE TITLE
Escoria is not supporting Godot's cutout animation?

### ISSUE THREAD

**Issue by Kubees** [godotengine/escoria#31]
Hey!

I am working on "player" node for my game. It works just fine, it follows orders, goes to objects, interacts with them. Huge issue comes, when I try to execute animation. As you can see on picture down below, my "player" node does not use AnimatedSprite type of node. Instead, "sprite" node is just a basic Sprite type of node, that servers as a root for other nodes of Sprite type. It has around 60 fully riged child nodes, I believe, that are animated with cutout animation, not by AnimatedSprite.

![bla](https://user-images.githubusercontent.com/20991844/29997665-5b83e4fe-9019-11e7-8c36-3ac1eff7e439.png)

After creating script containing these informations, that describe, when to use which animation (it is just for testing purposes, I just want to change it to something else when player starts to walk)...
```
const dir_angles = [360]

const directions = ["side_base", 1]

const idles = ["diagonal_base", 1]

const speaks = ["front_base", 1]
```
...and after testing the whole thing out, well... nothing happens! Player is standing, without doing any motion, and when I click on something, it just goes invisible and never comes back. It is actually moving, but it disappears.

I checked player.gd and it looks like cutout animation is not supported, well I think by looking at this code in 304th line...

`if p.is_type("Sprite") || p.is_type("AnimatedSprite"):`

...and only AnimatedSprite will work fine, but I can't use it, because I need smooth animations and sheets for AnimatedSprite types of node would be a lot bigger, than using a riged one.

I also tried to do so with "item", not "player". In item.gd, there is nothing about AnimatedSprite, there is just get_node("animation"), so I thought that I would make player as an "item" by using item.gd, but it seems that it doesn't support cutout animation either.

So, my question! Am I right that Escoria is currently not supporting cutout animations? How to overcome this problem? Cutout animation is crucial for my game, I want to use it a lot. I was looking for something like Adobe Flash, and this looked like it. I need help, game using image sheets will be just toooo big and I am not talking about harder editing and fine tuning of those sheets. Thank you in advance!

**Comment by fleskesvor** [comment]
I'm not familiar with cutout animation at all, but as far as I can tell by looking at the code, it uses animation frames directly, which in principle could be pretty much anything in Godot, so in theory, I think that should work. Looks like the only thing that check on the 304th line is used for is pushing sprites on an array, which is then used for color modulating sprites.

Are "side_base", "diagonal_base" and "front_base" actual keyframes in your AnimationPlayer? I don't suppose you have a minimal example of a cutout animated player character? I couldn't find one in the example projects.

**Comment by Kubees** [comment]
Oh, okay. I tried it doing with cutout animation on other newly created node "player" and it works just fine. It works! I wonder why the other one doesn't, though it is absolutely identical.

After further investigation and trying, I found out, that it can be animated with cutout animation, but root node HAS to stay on the same place forever! So, that means that I keyframed also the very root of "player" node, causing the whole problem.

I am just about to jump into my original "player" node and try to patch it, hopefully it will work. Oh, and the animation, "diagonal_base" etc., they [are actually animated like so.](https://youtu.be/a9HRTBoR1JA)

**Comment by Kubees** [comment]
As I said, cutout animation is working perfectly, but the root node can't be animated, it can't even have a keyframe assigned. [Here is a little preview, take a look!](https://youtu.be/QTAQ3PR8el8) And thank you for your time and will to help me, @fleskesvor !

**Comment by fleskesvor** [comment]
Awesome that you got it to work! :smile: If it's not too much trouble, could you post a screenshot of your player node in the scene tree, since I haven't managed to wrap my head around how exactly it's set up? I feel like an example of a cutout animated player character would be a good candidate for the list of improvements in #22.

**Comment by punto-** [comment]
There's no reason why keyframes on the root node wouldn't work, unless they're positions and the scene is being moved at the same time by the game (like a walk animation). But any other values would work, the game doesn't care about the content of the animation..‎ if you want the scene to move in place you need to put everything on a node child of the root, because the root might get moved by the game..                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: EivindSent: Sunday, September 3, 2017 7:15 PMTo: godotengine/escoriaReply To: godotengine/escoriaCc: SubscribedSubject: Re: [godotengine/escoria] Escoria is not supporting Godot's cutout animation? (#31)Awesome that you got it to work! 😄 If it's not too much trouble, could you post a screenshot of your player node in the scene tree, since I haven't managed to wrap my head around how exactly it's set up? I feel like an example of a cutout animated player character would be a good candidate for the list of improvements in #22.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/godotengine/escoria","title":"godotengine/escoria","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/godotengine/escoria"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fleskesvor in #31: Awesome that you got it to work! :smile: If it's not too much trouble, could you post a screenshot of your player node in the scene tree, since I haven't managed to wrap my head around how exactly it's set up? I feel like an example of a cutout animated player character would be a good candidate for the list of improvements in #22."}],"action":{"name":"View Issue","url":"https://github.com/godotengine/escoria/issues/31#issuecomment-326834708"}}}

**Comment by Kubees** [comment]
@punto- Yep, got it! Thank you!

@fleskesvor Ofcourse! Here it is! As you can see, it is loooooooong! And it is still not all! I just cut half of it away, but it is same. So, you have root node of Node2D type called "player" and then sprite, which server as root node for all other sprites, some of them are roots for another one. I followed [Godot cutout animation tutorial here.](http://docs.godotengine.org/en/stable/learning/features/animation/cutout_animation.html) I did what they did. Then you select, what you want to have connected by bones and then hit ctrl+shift+B to create them.
![13](https://user-images.githubusercontent.com/20991844/30070810-eba8dbe6-9264-11e7-9f7b-bd7cd0113dc9.png)
You can set some of them to be IK bones, inverse kinematics. The whole chain ending with IK bone will adapt, as you move it. [This is from my setup, hope it servers as good example.](https://youtu.be/qsVCJ7XtuC0) As you can see from the node preview, you also have Position2D nodes as final child of chains. Why is that? You want to have final bone even for very last part of your body. What the bone does is, that it connects from one tile to another, it connects its origin points. Position2D serves as new origin point, connecting both itself and origin bone of last tile to make a bone. Here is an example.
![14](https://user-images.githubusercontent.com/20991844/30071168-17c72dee-9266-11e7-8c2b-88bb216c33f4.png)

**Comment by punto-** [comment]
That should be fine.. The scene for the main character in Dog Mendonca was
similar (I could only find this screenshot with a bunch of the branches
without expanding). We didn't use IK tho, that looks cool..[image: Inline
images 1]

**Comment by fleskesvor** [comment]
Thanks for the example, @Kubees, and for the information, @punto-. I think I might take a stab at making a stick figure cutout animated player when I have time. Would be useful to know.

**Comment by StraToN** [comment]
Is the problem fixed for you @Kubees ? Can I close the issue?

**Comment by Kubees** [comment]
Yep, it is, thanks StraToN!

Once again for anybody wondering in the future,  cutout animation is supported, but root node of that node being animated must stay in place and can't have scale, rotation or position key assigned.
