### ISSUE TITLE
Clean up tool code and create icons for all remaining classes

### ISSUE THREAD

**Issue by dploeger** [godotengine/escoria#343]
As a game developer using Escoria, I'd like to see only nodes and ressources relevant to my work and have visual indications about the different node types I use in my games.

As an Escoria developer I'd like to make sure, only relevant classes are using then `tool` keyword. Relevant classes are the ones, that are directly used in the editor (e.g. as an editable node or a ressource). All other classes should have the `tool` keyword removed.

Additionally, all classes using the `tool` keyword should have icons depicting the specific use of the class. This can be achieved in this way:

`class_name ESCSomeClass, "res://path/to/icon.svg"`

According to the Godot specs, Editor icons should be 16x16 SVG graphics. See the [documentation](https://docs.godotengine.org/en/stable/development/editor/creating_icons.html) for specifics.

**Comment by StraToN** [comment]
I think I didn't exactly get what you meant about `tool` keyword at the time of issue creation. 
As far as I know, `tool` only means that this script runs inside the editor (2D or 3D) so that its `_process()` function reflects its actions there instead of only in game.

As an example, this was used in previous Escoria (and would be useful to keep btw) on ESCPlayer, so that the character scales when dragging him around the ESCTerrain, so you can see how it will scale around the room directly, allowing you to tune the ESCTerrain `scale_min` and `scale_max`.

**Comment by dploeger** [comment]
Yes. I misunderstood it and thought that only nodes with the keyword would show up in the node selection. I removed some occurrences of `tool` in my upcoming PR nonetheless because they had no apparent effect.
