### ISSUE TITLE
Documentation idea(s)

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#45]
I'm seriously considering Godot and Escoria for a point 'n click adventure game, because Unity assets are sometimes quite cumbersome and I have a hunch fighting with black-box assets could be replaced with doing things myself. Hoping that this is a valid assessment, I need to investigate Escoria properly.

It would be valuable to have a section of the Flossmanuals documentation, very early on, about best practices in the file system, related to installation. Like that `device` is the root of the project.

Parts of the documentation feel like everything's laid out really well and other parts feel like the reader should really figure things out. I got something going with the documentation but the consistency feels a bit off...

For example

https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/how-to-start-your-escoria-project/

says "You want to copy the Escoria folder and rename that copy to whatever suits you, like the codename of your project. Once it’s done, open Godot by clicking the file you downloaded earlier, this will open the Godot project manager window."

Apparently the "Escoria folder" is the Git checkout or Zip file, and it should be copied in its entirety. Referring to a file downloaded earlier sounds like maybe it would be the Zip file or something, when "launch Godot" would actually be clearer, though it's fewer words.

One "best practice" to point out would be deleting the `.git` path if it's there. It's kind of obvious, but because you're trying to be very explicit (a good thing!) maybe pointing this out is worth it. This will allow developers to init this as their own Git repository.

A developer may wonder if it's possible to start with an empty project and just copy/create certain files, and if so which ones?

Anyway, using the Git repository brings its own stuff with it, and it looks like the correct assets, but not everything is there. What if they were removed from the repository and the documentation updated to say "Download the entire flossmanuals fork as a Zip file or `git clone https://github.com/flossmanualsfr/escoria.git flossmanuals-escoria`" or something?

https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/creat-your-scene/

There it might be valuable to say the template scene should be copied under `device/` for clarity.

It might also be clearer if the `scenes` directory were called `resources` or `assets` because that's what it's apparently about.

Issue #5 would of course be helpful in this as well :)

**Comment by fleskesvor** [comment]
Yes, I 100% agree that there needs to be better documentation and examples on best practices and a better project structure, because I think a developer is much more likely to have a good experience with Escoria if they don't unintentionally make a huge mess of their project from the get-go.

This has been discussed briefly in #22 and #44, and I think the consensus is that every scene that a developer is likely to want to tweak, like dialoges, verb bars/action coins, inventory, etc. should be placed within logically named directories (preferably with their own READMEs), and not partially in globals/, as the case is now. It would also be great with a better demo, which teaches basic concepts as well as how to organise custom content to make it easier to re-use assets.

I think a good directory structure for custom assets might look something like this:

    scenes/
    ├── characters
    │   ├── npc1
    │   ├── npc2
    │   ├── npc3
    │   ├── player1
    │   └── player2
    ├── items
    │   ├── axe
    │   ├── banana
    │   ├── newspaper
    │   └── red_herring
    └── rooms
        ├── beach
        ├── finale
        ├── forest
        └── intro

Maybe "scenes" is a misleading term for someone new to Godot, and it may well that "assets" is a better name, but I think it might be best to stick to this terminology and emphasize that a playable location is called a "room", which is also what it's called in AGS and SCUMM. The main benefit of sticking to this terminology, as I see it, is that it avoids confusion when asking developers more experienced with Godot for help.

**Comment by mjtorn** [comment]
Yet another documentation finding: If the documentation said to check "Screen Size Override" I think that'd help, because it gives me a full-hd-resolution window. Haven't tested in my 720p master branch, but just leaving this note here.

**Comment by mjtorn** [comment]
Because `device/project.godot` has some settings I believe are custom for Escoria, it would be great to have helpful descriptions for them. http://docs.godotengine.org/en/3.0/classes/class_projectsettings.html

It would help explain why there is a "Use custom camera" setting for example, because I only don't know what it means, I don't know why the regular camera isn't enough.

**Comment by fleskesvor** [comment]
@mjtorn I'm all for using `actors` instead of `characters` if that's already a convention. The ScummVM wiki has several references to the word "actor" in this context, so I believe you're right, like in this list of debug codes:

http://wiki.scummvm.org/index.php/SCUMM/Debug_Codes

I don't think the official Godot docs is the right place for Escoria specific documentation, since Escoria is just one of many possible frameworks, but there is an official documentation included in the source:

https://github.com/godotengine/escoria/blob/master/doc/esc_reference.md

It's severly lacking though, but maybe adding a proper GitHub wiki to the repository would be a good idea?

**Comment by mjtorn** [comment]
@fleskesvor I meant that URL for reference purposes, it reads like it's possible to somehow make the settings "richer" by adding more verbose names and such to them. I'm still stuck trying to interrogate the game camera (and understanding what it says, this is like the movie Arrival), so I can't make a PR about that. I wouldn't even know what to write there.

A wiki could be a good idea, but I think the flossmauals docs are good enough to expand upon. Adding a wiki runs the risk that not much ends up there, or that the information gets scattered, when having one solid document(ation) carries more value.

As a general digression, the flossmanuals docs would also benefit from more inter-linking. Like the [The Items](https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/the-items/) chapter is great, it links to animations, but it does not link to [Scene composition](https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/the-items/) which talks about "how can place your artworks in the game to compose your scenes and how the mouse can _interact with items_." (emphasis mine)

Structured links like "Read more in chapter" may be quicker to set up in a wiki, I don't know, but going through things like this is hard work and the flossmanuals are, like I said, good enough.

A wiki would have to essentially start off with copypasting all the content and deprecating the old docs. I don't know if that's the best use of resources just now. Whoever wants to spend time on the documentation may pitch in.

But my current battle is elsewhere ;)

**Comment by mjtorn** [comment]
I put some effort into figuring out if esc scripts can help here, like `camera_set_target` and noticed that the `:load` event isn't documented. Is this what happens when the script file is loaded?

If I want a script to load when the game starts, can I name the script after the main scene?

Just in case this is documented, it's probably somewhere where my stupid brain couldn't find it :D

**Comment by fleskesvor** [comment]
Yes, you're right. The Flossmanuals tutorial is very good, and it would be better to adjust it for 3.0 and expand on it, rather than begin from scratch. That documentation is maintained by someone else though, and the source isn't open for contributions, as far as I know.

I'm not sure about the `:load` event. Where did you find it?

**Comment by mjtorn** [comment]
```
$ git grepn :load
device/game/game.esc:1::load
device/globals/global_vm.gd:552:        ret.append(":load\n\n")
device/quick_save.esc:1::load
```

And on the subject of maintenance of documentation, is this person active in the project or on irc? Because if the documentation is stale, and hard to update, that's actually a case for using the wiki.

Here are roughly two cents from me:

I also realized an argument for the wiki; I've been thinking that until Escoria is made into an asset by someone (I will not have time to even consider it) and if things get sorted otherwise, I'd be interested in having a fork of Escoria, **but** _only_ to add my own scenes and crap as a submodule, maybe even have the heavy binary assets as a separate submodule.

This may turn out to be a decent idea until there is an asset, and even then if the code base is unstable in the sense that things get cherry-picked from the rewrite branch etc. Either way, there should be no asset until the APIs can be considered stable, which very few, nay, no people can say in advance if things are going into a rewrite.

As long as the documentation doesn't get insanely fractured and as long as the wiki would start off as a copy of flossmanuals.

**Comment by mjtorn** [comment]
The documentation doesn't say `action_menu` has to be a child of `game`, this should be fixed.

**Comment by mjtorn** [comment]
The [Items](https://fr.flossmanuals.net/creating-point-and-click-games-with-escoria/the-items/) documentation says _"When a Control node is the root, the script will take all input from the root node, so no area node is necessary. The root node can be any type of Control, for example TextureFrame, or TextureButton."_.

A nice addition might be to point out that a `TextureButton`, when it has no texture, is transparent, which makes it useful for pseudo-items that are painted onto the screen but not meant to be picked up or anything. Like looking at a painting on the wall which is drawn onto the wall background.

**Comment by fleskesvor** [comment]
Yes, that's useful and should go in the docs.

Another option is to use an Area2D node for the item, which allows you to draw a click shape with editor tools. That requires a bit of setup though, since the background can't be a Control node, and the process is currently not documented at all.

**Comment by mjtorn** [comment]
There should also be a documented way of doing these types of areas with polygons.

I have no idea what a transparent polygon here is, especially one that doesn't complain about colliders and such.

Also when they overlap - say a book isn't known to be among other books until the books have been looked at - it would be nice if the documentation pointed out that the specific book must be a `Node2D` with a `global_id` so that esc script `set_active` can work.

It must be a `Node2D` for `active`. It must have a `global_id` because that's what esc acts on.

It also has to be underneath the node that causes the activation, like a next sibling, or it won't receive clicks for the overlapping area.

**Comment by mjtorn** [comment]
@fleskesvor that's what I meant with complaining about colliders, couldn't remember the exact error, but it says that `Area2D` has no shape without children of certain types etc. I don't currently need it, so that's fine by me for now ;)

**Comment by fleskesvor** [comment]
Yes, that definitely needs to go into the documentation. You can see examples of Area2D items in this branch:

https://github.com/fleskesvor/escoria/tree/remove-pnm-files?files=1

The branch hasn't been merged in Daïza because the inventory doesn't work properly, and it's also not compatible with 3.0 anymore.

**Comment by fleskesvor** [comment]
I opened flossmanualsfr/escoria#15 to suggest that the Floss Manuals tutorial is opened for contributions.

**Comment by mjtorn** [comment]
Pretty much everything is broken and undocumented wrt inventory. One big deal is how to document the ability to have in-game buttons. Another one is animating the inventory.

I will push a PR for analysis as soon as I can.

**Comment by mjtorn** [comment]
Having a player's `dialog_pos` (Position2D child node) is undocumented.

Besides this, when the character stands at (0, 0) in his scene, the position node needs to be somewhere else to align with the character's head. I do not understand this as it's not documented, or the transforms and projections are not explained in a place that I could find :(

**Comment by mjtorn** [comment]
Once #151 is merged, it should be known that there's a field for conflicts in the CSV. It should also be known that use of double-quotes in comments is discouraged, because they're not escaped properly, and thus may lead to unexpected results.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
