### ISSUE TITLE
Using only dialog/speech identifiers

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#59]
In my prototype, the player char can "pick up" the desk, which actually puts a key in his inventory.

It looks like this

```
:look
debug "My desk"
say player player_look_desk:"My desk"

:pick_up
> [!i/office_key]
	say player player_find_key:"The key to my office"
	set_global i/office_key true
```

To me it feels illogical that this action would disappear altogether only because `i/office_key` has been set.

I propose this type of functionality and syntax, which is a shorthand for saying lines defined elsewhere, for example fallbacks.

```
> [office_key]
    say player pick_up_fallback:
```

The terminal `:` would look up the ID `pick_up_fallback` and say that line.

Ideas?

**Comment by fleskesvor** [comment]
Yes, this functionality should be supported somehow, since it would be bad to have to duplicate dialogue from fallbacks whenever some action makes the options under it inaccessible.

Another option might be that the framework should be able to tell that none of the options under it can be executed and revert to fallbacks, but if fallbacks isn't desirable in some cases, that might be hard to override, so perhaps it's best to explicitly trigger fallbacks.

There are probably few cases where identifiers need to be changed over the course of development, unlike actual dialogue, which might be subject to fixing of typos, refinement, etc., so using identifiers to explicitly trigger dialogue sounds like a good idea to me.

**Comment by dploeger** [comment]
After a rewrite from scratch, Escoria will be re-released in the coming weeks. Because of this, we're closing this issue, because it relates to the old code. If the issue also regards the rewritten code, please feel free to reopen it.

Thanks
