### ISSUE TITLE
What about the use_custom_camera setting?

### ISSUE THREAD

**Issue by mjtorn** [godotengine/escoria#60]
It was discussed in #54 that this setting should remain in the code for now. It works while it's set to `true`, but it's not documented behavior anywhere.

@punto- or @StraToN should be summoned to state if this is a thing that needs to exist, and if so, where to document what it does exactly.

Of course, being a discussion issue for something that currently works, anyone can pitch in :)

My two cents say it has to go.

**Comment by mjtorn** [comment]
I was looking at what settings are available, if some others should suffer the fate of #71 and remembered this.

Could someone with ownership take a stand on this and/or make a patch to remove it or at least green-light a removal?

**Comment by StraToN** [comment]
I think this was a debug property created during Dog Mendoza's development. The idea was to have a single boolean debug property to check in order to divide the screen size by 2, instead of having to set a custom viewport size each time you required to.

If such user-properties are required, I guess the user would prefer to declare their behaviour in a specific user-defined GDScript so they don't interfere, and user doesn't modify Escoria's core scripts. This one could be an example.

So my 2 cents are: yes (to remove) and no (put them away).

Also about documentation: we will probably start thinkin about it very soon (#68)

**Comment by fleskesvor** [comment]
> edit: I made some tests and the demo scene actually won't render if use_custom_camera=false. I'll make more tests tonight.

Yes, with `use_custom_camera=false` only the verb menu is visible in my testing. I agree that we should remove this now, and if the need arises, we re-implement the intended feature.
