### ISSUE TITLE
Action menu prevents walking

### ISSUE THREAD

**Issue by fleskesvor** [godotengine/escoria#98]
When setting an action menu from the project settings, clicking the background to walk does not work. This functionality was introduced with #79 and adapted into #80, so a git bisect to pin down this issue should start from 895a5337a2586b21057d74c05bf6fece9ab7032b^.

**Comment by mjtorn** [comment]
On Fri, Mar 23, 2018 at 11:42:23PM -0700, Eivind wrote:
>When setting an action menu from the project settings, cicking the background to walk does not work. This functionality was introduced with #79 and adapted into #80, so a git bisect to pin down this issue should start from 895a5337a2586b21057d74c05bf6fece9ab7032b^.

Is this a problem?

Mentioned on IRC that having messed about extensively (exclusively) with
action menus while prototyping, this feels like the natural way of things.

One problem that would have to be solved if this was altered is clamping.

Say the player opens the menu at the left edge of the room on `shrubbery`
and walks 9000 pixels to the right.

Would the action menu just float along at the edge of the screen in a long
room like that?

Would the action menu automatically close? But only when it would be
scrolled out?

My recommendation is stating this in documentation as a feature and having
a `ProjectSettings` toggle for the behavior if someone wants to write
a patch.

PS.

Been a while since I played the LucasArts games with these, but I think
they required you to push the RMB down and choose an action by releasing
over a button. I wouldn't seek to emulate that behavior because it offers
little extra value and is probably harder to code up.

**Comment by fleskesvor** [comment]
> Is this a problem?

It is if you have a scrolling room with interactive elements outside of the viewport, because then there's no way for you to walk to get to them. I also don't think it's intuitive that clicking on the ground doesn't make the player move. In Full Throttle, which has an action menu/verb coin, you can click on the ground to move. I don't remember other specific examples, but I think this is the norm.

> Say the player opens the menu at the left edge of the room on `shrubbery`
and walks 9000 pixels to the right.

I don't think this will be a problem, because if the action menu is open somewhere, and you want to move in the opposite direction, you'd have to click on the ground where you want to walk, which would close the menu anyway, right? Unless walking was triggered from an esc script, in which case we'd have to write code for closing the action menu, if that isn't implemented already.

> Been a while since I played the LucasArts games with these, but I think
they required you to push the RMB down and choose an action by releasing
over a button. I wouldn't seek to emulate that behavior because it offers
little extra value and is probably harder to code up.

Yes, both Curse of Monkey Island and Full Throttle required left-click+hold to bring up the action menu. Right-click was used for other things; the inventory in FT and the most obvious action in CoMI, eg. "talk" when clicking an NPC.

I agree that just clicking to open the action menu is good enough for now, but we can revisit the topic later if there's demand for such an action menu.

**Comment by StraToN** [comment]
The action menu doesn't act as a blocker in LucasArts games. If you select an action an click anywhere but on an item, the player simply walks to that location. At least this is the functionment for SCUMM V0 (Maniac Mansion) to 6 (Sam & Max Hit the Road CD).
Later versions (7 and 8) are used by Full Throttle, CMI and The Dig. While the first 2 use a blocking action menu, the cause is the use of left mouse button having to be pressed for the menu to keep being displayed. The Dig uses another design with one left mouse action and one right mouse action (usually look).

Studying these design choices is actually a very interesting subject to write about. I'll start a blog post.

**Comment by mjtorn** [comment]
I can't reproduce this anymore!

Opening the RMB AM doesn't block walking anymore. Is it because it's a `Container` now so it's bounded and the click goes outside those bounds?

**Comment by fleskesvor** [comment]
> Opening the RMB AM doesn't block walking anymore. Is it because it's a `Container` now so it's bounded and the click goes outside those bounds?

I rebased my ui-templates branch, #114, on master yesterday, the action menu is a `Container` and I'm still experiencing this issue. The action menu is part of the hud in my branch though, instead being instanced into the room scene. Come to think of it, I believe `game.gd` makes some assumptions about where the player node will be in the scene tree relative to the action menu, which is not accurate anymore in my branch.

**Comment by fleskesvor** [comment]
I've looked into this issue, and I'm re-opening it, since I don't think this is working as intended for all use cases. The regression was introduced by this line:

https://github.com/godotengine/escoria/commit/fa8723ad29a9f069e13e776698af1e020b8ad5e4#diff-3246357049f1e0f16e0ecfc81ae63cf0R152

Which makes the assumption that all games with an action menu will have a blocking inventory, which means that it should not be possible to move while it's open. I don't think this is always the case, and it's difficult for a game developer to understand that this is what's happening in the demo scene, since the inventory is transparent. Pressing Tab to close the invisible inventory enables walking until Tab is pressed again. I'm not sure what the best solution for this is, but I'd think that closing the inventory on click makes more sense than blocking walking altogether, and it's also more consistent with the behaviour here:

https://github.com/godotengine/escoria/blob/master/device/globals/game.gd#L278

Although, I don't know if it's needed there, since pressing Esc already hides the entire hud while bringing up the menu; pressing Esc again brings up the hud again, but with the inventory being closed in the meantime.

I agree that there are definitely cases where this is the desired behaviour, but I think this should be an exported var (`is_collapsible`?)  in the inventory rather than it being the only option and dependent on the action menu, since a developer might want a collapsible inventory with one- or two-click interfaces as well, and the opposite might also be true for both varieties.
